### ISSUE TITLE
Enable VSCode Debugger for CloudFunction Development

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet-next#118]
We want to add VSCode settings so that developers can use VSCode's debugger function when developing "CloudFunctions"
This makes it easier for developers to identify the cause of problems and speeds up development.
If you agree, please approve the associated pull request.

## Improvement details

- Added debug configuration file for VSCode
- Added ESBuid settings to enable debugging during development

**Comment by KishiTheMechanic** [comment]
LFG🚀
